name: Deploy to GCP VM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GOOGLE_SSH_MAC_PVT_KEY }}
          project_id: turing-gpt

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GOOGLE_SSH_MAC_PVT_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GOOGLE_SSH_MAC_PVT_KEY }}
          script: |
            cd /home/cot-generation-tool
            ./deploy.sh deploy
